### ISSUE TITLE
REMC tutorial does not run through

### ISSUE THREAD

**Issue by Clownshift** [bio-phys/complexespp#5] opened 2022-03-09 09:59 UTC
I think there might be multiple problems. So far I identified the following:
If the REMC simulation was started multiple times, the log file is appended. However, the demux tool cannot handle appended log files, apparently.

I suppose this is an issue by itself, that needs to be solved. (Will create separate issues eventually...)

**Comment by Clownshift** [comment] 2022-03-09 13:53
#6

**Comment by kain88-de** [comment] 2022-03-11 07:26
duplicate of #6

**Closed by kain88-de** 2022-03-11 07:26 UTC
Labels: bug, enhancement
